openapi: "3.0.0"
info:
  version: 3.0.0
  title: dataliquid store
  description: A sample API that uses a store as an example
  termsOfService: https://www.dataliquid.io/terms/apis/
  contact:
    name: API Support Team
    email: support@dataliquid.com
    url: http://dataliquid.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.dataliquid.com/store/api/v1
paths:
  /persons:
    get:
      description: |
		Retrieve persons
      operationId: findPersons
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: persons response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
